// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace WebApplication2DB.Data.Visitor
{
    public partial class VisitorlogdbContext : DbContext
    {
        public VisitorlogdbContext()
        {
        }

        public VisitorlogdbContext(DbContextOptions<VisitorlogdbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Visitor> Visitor { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.Entity<Visitor>(entity =>
            {
                entity.Property(e => e.CheckIn)
                    .HasColumnType("datetime")
                    .HasColumnName("check_in");

                entity.Property(e => e.CheckOut)
                    .HasColumnType("datetime")
                    .HasColumnName("check_out");

                entity.Property(e => e.Department)
                    .HasMaxLength(50)
                    .HasColumnName("department");

                entity.Property(e => e.Description)
                    .HasMaxLength(50)
                    .HasColumnName("description");

                entity.Property(e => e.FirstName)
                    .HasMaxLength(50)
                    .HasColumnName("first_name");

                entity.Property(e => e.Image).HasColumnName("image");

                entity.Property(e => e.LastName)
                    .HasMaxLength(50)
                    .HasColumnName("last_name");

                entity.Property(e => e.Organization)
                    .HasMaxLength(50)
                    .HasColumnName("organization");

                entity.Property(e => e.Phone)
                    .HasColumnType("decimal(18, 0)")
                    .HasColumnName("phone");

                entity.Property(e => e.Visiting)
                    .HasMaxLength(50)
                    .HasColumnName("visiting");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}